# Generated by Django 5.1.6 on 2025-05-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.CharField(max_length=128, unique=True, verbose_name='Токен'),
        ),
    ]
