# Generated by Django 5.1.6 on 2025-05-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_systemtoken_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemtoken',
            name='token',
            field=models.CharField(max_length=255, verbose_name='Системный токен'),
        ),
    ]
