# Generated by Django 5.1.6 on 2025-05-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='Тикер')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сектор')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отрасль')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('market_cap', models.FloatField(blank=True, null=True, verbose_name='Капитализация рынка')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(verbose_name='Дата операции')),
                ('card_number', models.CharField(blank=True, max_length=16, verbose_name='Номер карты')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Категория')),
                ('mcc', models.CharField(blank=True, max_length=4, verbose_name='MCC')),
                ('description', models.TextField(verbose_name='Описание')),
                ('bonuses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бонусы')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
            ],
        ),
    ]
