# Generated by Django 5.1.6 on 2025-05-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figi', models.CharField(max_length=12, unique=True, verbose_name='FIGI')),
                ('ticker', models.CharField(max_length=10, verbose_name='Тикер')),
                ('name', models.CharField(max_length=255, verbose_name='Название облигации')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('maturity_date', models.DateField(verbose_name='Дата погашения')),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Номинал')),
                ('coupon_quantity_per_year', models.IntegerField(verbose_name='Количество купонов в год')),
                ('floating_coupon_flag', models.BooleanField(default=False, verbose_name='Плавающий купон')),
                ('perpetual_flag', models.BooleanField(default=False, verbose_name='Бессрочная облигация')),
                ('amortization_flag', models.BooleanField(default=False, verbose_name='Амортизация долга')),
                ('exchange', models.CharField(max_length=50, verbose_name='Торговая площадка')),
                ('trading_status', models.CharField(max_length=50, verbose_name='Режим торгов')),
            ],
            options={
                'verbose_name': 'Облигация',
                'verbose_name_plural': 'Облигации',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figi', models.CharField(max_length=12, unique=True, verbose_name='FIGI')),
                ('ticker', models.CharField(max_length=10, verbose_name='Тикер')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сектор')),
                ('country_of_risk', models.CharField(max_length=2, verbose_name='Код страны риска')),
                ('country_of_risk_name', models.CharField(max_length=100, verbose_name='Страна риска')),
                ('exchange', models.CharField(max_length=50, verbose_name='Торговая площадка')),
                ('lot', models.IntegerField(verbose_name='Лотность')),
                ('nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Номинал')),
                ('trading_status', models.CharField(max_length=50, verbose_name='Режим торгов')),
                ('ipo_date', models.DateField(blank=True, null=True, verbose_name='Дата IPO')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
