# Generated by Django 5.1.6 on 2025-05-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
