# Generated by Django 5.1.6 on 2025-05-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Системный токен')),
            ],
            options={
                'verbose_name': 'Системный токен',
                'verbose_name_plural': 'Системные токены',
            },
        ),
    ]
