# Generated by Django 5.1.6 on 2025-05-12 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_systemtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemToken',
        ),
    ]
